#spring.application.name=SpringBootHandson

#spring.application.name=springboot-mvc
#spring.mvc.view.prefix= /views/
#spring.mvc.view.suffix= .jsp

#spring.datasource.url=jdbc:mysql://localhost:3306/tutorial
#spring.datasource.username=root
#spring.datasource.password=2000
#spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQL8Dialect
#
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=update

spring:
  datasource:
    url: jdbc:mysql://root:OupitWfEdeniRnVwHqsbNYyAeSQCHwtJ@interchange.proxy.rlwy.net:35494/railway
    username: root
    password: OupitWfEdeniRnVwHqsbNYyAeSQCHwtJ
    driver-class-name: com.mysql.cj.jdbc.Driver
    ##    url: jdbc:mysql://localhost:3306/tutorial
    #    username: root
    #    password: 2000
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  redis:
    url: redis-cli -u redis://default:n1u2PDNqtBP1g9Cu7cOnoVw31AlysLi8@redis-15090.c212.ap-south-1-1.ec2.redns.redis-cloud.com:15090
#    host: localhost
#    post: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: kc.nitish2@gmail.com
    password: jbcmxyilbhezrzrl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path : /test


